services:
  mysql:
    image: mysql:5.7
    volumes: [ mysql_data:/var/lib/mysql ]
    env_file: [ ./config/db.env ]
    networks: [ backend ]
    restart: always

  wordpress:
    image: wordpress:latest
    depends_on: [ mysql ]
    ports: [ 8000:80 ]
    env_file: [ ./config/wp.env ]
    networks: [ backend ]
    restart: always

volumes:
  mysql_data: {}
networks:
  backend:
